CREATE TABLE pages (id BIGINT(7) NOT NULL AUTO_INCREMENT,
title VARCHAR(200), content VARCHAR(10000),
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id));

CREATE TABLE phrases (id int(11) NOT NULL AUTO_INCREMENT,
phrase VARCHAR(200), PRIMARY KEY(id));

CREATE TABLE urls (id int(11) NOT NULL AUTO_INCREMENT,
url VARCHAR(200), PRIMARY KEY(id));

CREATE TABLE foundInstances (id int(11) NOT NULL AUTO_INCREMENT,
urlId int(11),phraseId int(11), occurrences int(11), PRIMARY KEY(id));


CREATE DATABASE wikipedia;

CREATE TABLE `wikipedia`.`pages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(`id`));
  
CREATE TABLE `wikipedia`.`links` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`fromPageId` INT NULL,
	`toPageId` INT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`));
